services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sso_easy_station
    ports:
      - 27017:27017
  postgresdb:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/data/db
    environment:
      - 'POSTGRES_USER=easy_station'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=easy_station'
    ports:
      - 5432:5432
volumes:
  mongodb-data:
  postgres-data:
